# .travis.yml using container-based infrastructure (https://github.com/jtilly/R-travis-container-example)

# use c as catch-all language
language: c

# use containers
sudo: false

# install R: use r-packages-precise (https://cran.r-project.org/bin/linux/ubuntu/precise/) 
# as source which is white listed (https://github.com/travis-ci/apt-source-whitelist/)
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev	
    - r-recommended

# cache local R libraries directory:
cache:
  directories:
    - ~/Rlib
    - $HOME/bin
    - $HOME/texlive

before_install:
  - export PATH=$HOME/bin:$HOME/texlive/bin/x86_64-linux:$PATH
  - chmod 755 ./.push_gh_pages.sh
  - chmod 755 ./ghgenerate.R


# install the package and dependencies:
# - create directory for R libraries (if not already exists)
# - create .Renviron with location of R libraries
# - install rmarkdown if not already installed
# - update all installed packages
# - execute proposal gen
install:
  - mkdir -p ~/Rlib
  - mkdir -p $HOME/bin
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-texlive | bash"
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-pandoc | bash"
  - Rscript -e 'if(!"rmarkdown" %in% rownames(installed.packages())) { install.packages("rmarkdown", dependencies = TRUE) }'
  - Rscript -e 'if(!"png" %in% rownames(installed.packages())) { install.packages("png", dependencies = TRUE) }'
  - Rscript -e 'if(!"googlesheets" %in% rownames(installed.packages())) { install.packages("googlesheets", dependencies = TRUE) }'
  - Rscript -e 'if(!"readr" %in% rownames(installed.packages())) { install.packages("readr", dependencies = TRUE) }'
  - Rscript -e 'if(!"data.table" %in% rownames(installed.packages())) { install.packages("data.table", dependencies = TRUE) }'
  - Rscript -e 'if(!"ggplot2" %in% rownames(installed.packages())) { install.packages("ggplot2", dependencies = TRUE) }'
  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'

script:
  - ./.push_gh_pages.sh
