language: r
cache: packages
install:
  - Rscript -e 'install.packages("rmarkdown")'
  - Rscript -e 'install.packages("png")'
  - Rscript -e 'install.packages("googlesheets")'
  - Rscript -e 'install.packages("readr")'
  - Rscript -e 'install.packages("data.table")'
  - Rscript -e 'install.packages("ggmap")'
  - Rscript -e 'install.packages("maps")'
  - chmod 755 .push_gh_pages.sh
  - chmod 755 ghgenerate.R
script:
  - ./.push_gh_pages.sh